### ISSUE TITLE
Features: error message in live-editor has not any CSS rules

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable.com-v2#4]
As in the title:
![screen shot 2017-09-12 at 14 24 49](https://user-images.githubusercontent.com/11849621/30326083-9d4a00c0-97c7-11e7-93ca-68f51bf40a9d.png)

Where: https://handsontable.com/features.html#tab-source

**Comment by krzysztofspilka** [comment]
Thanks, it has been fixed - we replaced the notification with the red dot being displayed in the top right corner of the editor.
